// Seed data for local/dev environments. Real destination photography must
// replace the placeholder imageUrl values before production use — see
// DESIGN.md for licensing requirements.

export const airports = [
  { iataCode: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom", countryCode: "GB", latitude: 53.3537, longitude: -2.275 },
  { iataCode: "LHR", name: "Heathrow Airport", city: "London", country: "United Kingdom", countryCode: "GB", latitude: 51.4700, longitude: -0.4543 },
  { iataCode: "LGW", name: "Gatwick Airport", city: "London", country: "United Kingdom", countryCode: "GB", latitude: 51.1537, longitude: -0.1821 },
  { iataCode: "STN", name: "Stansted Airport", city: "London", country: "United Kingdom", countryCode: "GB", latitude: 51.8860, longitude: 0.2389 },
  { iataCode: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom", countryCode: "GB", latitude: 52.4539, longitude: -1.7480 },
  { iataCode: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom", countryCode: "GB", latitude: 55.9500, longitude: -3.3725 },
  { iataCode: "BRS", name: "Bristol Airport", city: "Bristol", country: "United Kingdom", countryCode: "GB", latitude: 51.3827, longitude: -2.7191 },
  { iataCode: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom", countryCode: "GB", latitude: 55.8642, longitude: -4.4331 },
  { iataCode: "LPL", name: "Liverpool John Lennon Airport", city: "Liverpool", country: "United Kingdom", countryCode: "GB", latitude: 53.3336, longitude: -2.8497 },
  { iataCode: "BCN", name: "Barcelona–El Prat Airport", city: "Barcelona", country: "Spain", countryCode: "ES", latitude: 41.2971, longitude: 2.0785 },
  { iataCode: "BUD", name: "Budapest Ferenc Liszt International Airport", city: "Budapest", country: "Hungary", countryCode: "HU", latitude: 47.4298, longitude: 19.2611 },
  { iataCode: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "Portugal", countryCode: "PT", latitude: 38.7813, longitude: -9.1359 },
  { iataCode: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "Italy", countryCode: "IT", latitude: 45.6306, longitude: 8.7281 },
  { iataCode: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czechia", countryCode: "CZ", latitude: 50.1008, longitude: 14.26 },
  { iataCode: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France", countryCode: "FR", latitude: 49.0097, longitude: 2.5479 },
  { iataCode: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "Netherlands", countryCode: "NL", latitude: 52.3105, longitude: 4.7683 },
  { iataCode: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", city: "Rome", country: "Italy", countryCode: "IT", latitude: 41.8003, longitude: 12.2389 },
  { iataCode: "ATH", name: "Athens International Airport", city: "Athens", country: "Greece", countryCode: "GR", latitude: 37.9364, longitude: 23.9445 },
  { iataCode: "AGP", name: "Málaga–Costa del Sol Airport", city: "Malaga", country: "Spain", countryCode: "ES", latitude: 36.6749, longitude: -4.4991 },
  { iataCode: "ALC", name: "Alicante–Elche Airport", city: "Alicante", country: "Spain", countryCode: "ES", latitude: 38.2822, longitude: -0.5582 },
  { iataCode: "FAO", name: "Faro Airport", city: "Faro", country: "Portugal", countryCode: "PT", latitude: 37.0144, longitude: -7.9659 },
  { iataCode: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland", countryCode: "IE", latitude: 53.4264, longitude: -6.2499 },
  { iataCode: "KRK", name: "Kraków John Paul II Airport", city: "Krakow", country: "Poland", countryCode: "PL", latitude: 50.0777, longitude: 19.7848 },
  { iataCode: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland", countryCode: "PL", latitude: 52.1657, longitude: 20.9671 },
  { iataCode: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany", countryCode: "DE", latitude: 52.3667, longitude: 13.5033 },
  { iataCode: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark", countryCode: "DK", latitude: 55.6180, longitude: 12.6560 },
  { iataCode: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria", countryCode: "AT", latitude: 48.1103, longitude: 16.5697 },
  { iataCode: "OPO", name: "Porto Airport", city: "Porto", country: "Portugal", countryCode: "PT", latitude: 41.2481, longitude: -8.6814 },
  { iataCode: "TFS", name: "Tenerife South Airport", city: "Tenerife", country: "Spain", countryCode: "ES", latitude: 28.0445, longitude: -16.5725 },
] as const;

export const destinations = [
  { slug: "barcelona", city: "Barcelona", country: "Spain", countryCode: "ES", airportCode: "BCN", airportName: "Barcelona–El Prat Airport", imageSeed: "reelflights-barcelona" },
  { slug: "budapest", city: "Budapest", country: "Hungary", countryCode: "HU", airportCode: "BUD", airportName: "Budapest Ferenc Liszt International Airport", imageSeed: "reelflights-budapest" },
  { slug: "lisbon", city: "Lisbon", country: "Portugal", countryCode: "PT", airportCode: "LIS", airportName: "Humberto Delgado Airport", imageSeed: "reelflights-lisbon" },
  { slug: "milan", city: "Milan", country: "Italy", countryCode: "IT", airportCode: "MXP", airportName: "Milan Malpensa Airport", imageSeed: "reelflights-milan" },
  { slug: "prague", city: "Prague", country: "Czechia", countryCode: "CZ", airportCode: "PRG", airportName: "Václav Havel Airport Prague", imageSeed: "reelflights-prague" },
  { slug: "paris", city: "Paris", country: "France", countryCode: "FR", airportCode: "CDG", airportName: "Charles de Gaulle Airport", imageSeed: "reelflights-paris" },
  { slug: "amsterdam", city: "Amsterdam", country: "Netherlands", countryCode: "NL", airportCode: "AMS", airportName: "Amsterdam Airport Schiphol", imageSeed: "reelflights-amsterdam" },
  { slug: "rome", city: "Rome", country: "Italy", countryCode: "IT", airportCode: "FCO", airportName: "Leonardo da Vinci–Fiumicino Airport", imageSeed: "reelflights-rome" },
  { slug: "athens", city: "Athens", country: "Greece", countryCode: "GR", airportCode: "ATH", airportName: "Athens International Airport", imageSeed: "reelflights-athens" },
  { slug: "malaga", city: "Malaga", country: "Spain", countryCode: "ES", airportCode: "AGP", airportName: "Málaga–Costa del Sol Airport", imageSeed: "reelflights-malaga" },
  { slug: "alicante", city: "Alicante", country: "Spain", countryCode: "ES", airportCode: "ALC", airportName: "Alicante–Elche Airport", imageSeed: "reelflights-alicante" },
  { slug: "faro", city: "Faro", country: "Portugal", countryCode: "PT", airportCode: "FAO", airportName: "Faro Airport", imageSeed: "reelflights-faro" },
  { slug: "dublin", city: "Dublin", country: "Ireland", countryCode: "IE", airportCode: "DUB", airportName: "Dublin Airport", imageSeed: "reelflights-dublin" },
  { slug: "krakow", city: "Krakow", country: "Poland", countryCode: "PL", airportCode: "KRK", airportName: "Kraków John Paul II Airport", imageSeed: "reelflights-krakow" },
  { slug: "warsaw", city: "Warsaw", country: "Poland", countryCode: "PL", airportCode: "WAW", airportName: "Warsaw Chopin Airport", imageSeed: "reelflights-warsaw" },
  { slug: "berlin", city: "Berlin", country: "Germany", countryCode: "DE", airportCode: "BER", airportName: "Berlin Brandenburg Airport", imageSeed: "reelflights-berlin" },
  { slug: "copenhagen", city: "Copenhagen", country: "Denmark", countryCode: "DK", airportCode: "CPH", airportName: "Copenhagen Airport", imageSeed: "reelflights-copenhagen" },
  { slug: "vienna", city: "Vienna", country: "Austria", countryCode: "AT", airportCode: "VIE", airportName: "Vienna International Airport", imageSeed: "reelflights-vienna" },
  { slug: "porto", city: "Porto", country: "Portugal", countryCode: "PT", airportCode: "OPO", airportName: "Porto Airport", imageSeed: "reelflights-porto" },
  { slug: "tenerife", city: "Tenerife", country: "Spain", countryCode: "ES", airportCode: "TFS", airportName: "Tenerife South Airport", imageSeed: "reelflights-tenerife" },
] as const;
